@startuml
left to right direction
actor 科室管理员 as admin
actor 超级管理员 as superAdmin
user <|-- admin
user <|-- superAdmin
rectangle 《体温监测系统》{
admin -- (监控平台)
admin -- (历史记录)
superAdmin --> (床位管理)
superAdmin --> (设备管理)
superAdmin --> (路由管理)
superAdmin --> (账号管理)


(监控平台) ..> (体温监测) : 《include》
(监控平台) ..> (心电监测) : 《include》

(体温监测) ..> (体温：实时监控信息) : 《include》
(体温：实时监控信息) ..> (体温：实时体温记录) : 《include》
(体温：实时监控信息) ..> (体温：历史体温记录) : 《include》
(体温监测) ..> (体温：病人管理) : 《include》
(体温：病人管理) ..> (体温：停止监测) : 《include》
(体温：病人管理) ..> (体温：更换设备) : 《include》
(体温：病人管理) ..> (体温：更换床位) : 《include》
(体温：病人管理) ..> (体温：启用设备) : 《include》

(心电监测) ..> (心电：实时监控信息) : 《include》
(心电：实时监控信息) ..> (心电：实时心电记录) : 《include》
(心电：实时监控信息) ..> (心电：实时心率、呼吸率记录) : 《include》
(心电：实时监控信息) ..> (心电：历史心电记录) : 《include》
(心电监测) ..> (心电：病人管理) : 《include》
(心电：病人管理) ..> (心电：停止监测) : 《include》
(心电：病人管理) ..> (心电：更换设备) : 《include》
(心电：病人管理) ..> (心电：更换床位) : 《include》
(心电：病人管理) ..> (心电：启用设备) : 《include》


(历史记录) ..> (查询监测信息) : 《include》
(历史记录) ..> (导出监测信息) : 《include》

(床位管理) ..> (床位信息：增、删、改、查、导出) : 《include》
(设备管理) ..> (设备信息：增、删、改、查、导出) : 《include》
(设备管理) ..> (设备搜索) : 《include》
(路由管理) ..> (路由信息：增、删、改、查、导出) : 《include》
(账号管理) ..> (账号信息：增、删、改、查) : 《include》
}
@enduml